# See https://github.com/lowlighter/metrics for documentation

name: Metrics
on:
  schedule: [{cron: "0 16 * * *"}]  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Icons
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.icons.svg
          token: NOT_NEEDED
          base: ""

      - name:  Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token:  ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_achievements: yes
          plugin_achievements_display: compact

      - name:  Followers
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.people.followers.svg
          token:  ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_types: followers

      - name:  Wakatime
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-grahps, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

      - name:  General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token:  ${{ secrets.METRICS_TOKEN }}
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, languages
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_isocalendar: yes

          # Languages
          plugin_languages: yes
          plugin_languages_ignored: tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, scala
          plugin_languages_sections: most-used
          plugin_languages_limit: 4
